# Generated by Django 2.2.10 on 2020-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200502_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='S268CA6', max_length=7, verbose_name='Student code'),
        ),
    ]
