# Generated by Django 2.2.10 on 2020-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200502_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='SD83795', max_length=7, verbose_name='Student code'),
        ),
    ]
