# Generated by Django 2.2.10 on 2020-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200503_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='SE1851C', max_length=7, verbose_name='Student code'),
        ),
    ]
