# Generated by Django 2.2.10 on 2020-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200504_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='SAF52C2', max_length=7, verbose_name='Student code'),
        ),
    ]
