# Generated by Django 2.2.10 on 2020-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200502_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T87AB2C', max_length=7, verbose_name='Teacher code'),
        ),
    ]
