# Generated by Django 2.2.10 on 2020-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200503_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T5897C8', max_length=7, verbose_name='Teacher code'),
        ),
    ]
