# Generated by Django 2.2.10 on 2020-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20200504_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T1E31F4', max_length=7, verbose_name='Teacher code'),
        ),
    ]
