# Generated by Django 2.2.10 on 2020-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='6DC949', max_length=6, verbose_name='Code'),
        ),
    ]
