# Generated by Django 2.2.10 on 2020-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200502_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='7BBFD6', max_length=6, verbose_name='Code'),
        ),
    ]
