# Generated by Django 2.2.10 on 2020-05-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200502_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='C63E6C', max_length=6, verbose_name='Code'),
        ),
    ]
