# Generated by Django 2.2.10 on 2020-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200502_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='1D6965', max_length=6, verbose_name='Code'),
        ),
    ]
