# Generated by Django 2.2.10 on 2020-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200503_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='3C1967', max_length=6, verbose_name='Code'),
        ),
    ]
