# Generated by Django 2.2.10 on 2020-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200504_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='E9CCBD', max_length=6, verbose_name='Code'),
        ),
    ]
